name: Release
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test on node ${{ matrix.node }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 10, 12, 14 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  release:
    name: Github release & npm publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        if: success()
        run: npm run build

      - name: Semantic Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
